# Generated by Django 5.1.7 on 2025-04-05 06:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.CharField(max_length=500, unique=True)),
                ("main_domain", models.CharField(max_length=500, null=True, unique=True)),
                ("main_domain_ssl", models.BooleanField(default=True, null=True)),
                ("basic_auth_user_required", models.BooleanField(default=False)),
                ("allow_override", models.BooleanField(default=False)),
                ("access_file_name", models.CharField(default=".htaccess", max_length=500)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SitePreviewInstanceModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.CharField(max_length=500)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteAlternativeDomainModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("domain", models.CharField(max_length=500, unique=True)),
                ("domain_ssl", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="staticpatchcore.sitemodel"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuildModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("failed_at", models.DateTimeField(null=True)),
                (
                    "site",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="staticpatchcore.sitemodel"),
                ),
                (
                    "site_preview_instance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staticpatchcore.sitepreviewinstancemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SitePreviewTypeModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.CharField(max_length=500)),
                ("domain", models.CharField(max_length=500)),
                ("domain_ssl", models.BooleanField(default=True)),
                ("basic_auth_user_required", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="staticpatchcore.sitemodel"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sitepreviewinstancemodel",
            name="site_preview_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staticpatchcore.sitepreviewtypemodel"
            ),
        ),
        migrations.CreateModel(
            name="SiteSecurityKeyModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=500)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="staticpatchcore.sitemodel"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BasicAuthUserModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=500)),
                ("password_crypted", models.CharField(max_length=500)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="staticpatchcore.sitemodel"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("site_id", "username"), name="site_id_username_unique")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sitepreviewtypemodel",
            constraint=models.UniqueConstraint(fields=("site", "slug"), name="site_slug_unique"),
        ),
        migrations.AddConstraint(
            model_name="sitepreviewinstancemodel",
            constraint=models.UniqueConstraint(
                fields=("site_preview_type", "slug"), name="site_preview_type_slug_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sitesecuritykeymodel",
            constraint=models.UniqueConstraint(fields=("site_id", "key"), name="site_id_key_unique"),
        ),
    ]
